In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('C:/Users/rohit/OneDrive/Desktop/akshat programming/Movie Recommender System/tmdb_5000_movies.csv')
credits = pd.read_csv('C:/Users/rohit/OneDrive/Desktop/akshat programming/Movie Recommender System/tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies = movies.merge(credits, on='title')

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
movies = movies[['movie_id', 'title','overview','genres','keywords','cast','crew']]

In [8]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
import ast

In [10]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

In [11]:
movies.dropna(inplace=True)

In [12]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [15]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [16]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [18]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [19]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [20]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
1932,21338,Stone Cold,"Joe Huff (Brian Bosworth) is a tough, loner co...","[Action, Crime, Thriller]","[undercover, fbi, biker, cop, motorcycle gang]","[Brian Bosworth, Lance Henriksen, William Fors...",[Craig R. Baxley]
561,1997,Two Brothers,Two tigers are separated as cubs and taken int...,"[Adventure, Drama, Family]","[brother brother relationship, loss of brother...","[Maï Anh Le, Guy Pearce, Oanh Nguyen]",[Jean-Jacques Annaud]
3557,91586,Insidious: Chapter 2,The haunted Lambert family seeks to uncover th...,"[Horror, Thriller]","[haunted house, possession, demon, family, gho...","[Patrick Wilson, Rose Byrne, Ty Simpkins]",[James Wan]
4423,96534,My Last Day Without You,"On a one-day business trip to New York, a youn...","[Comedy, Drama, Romance]",[],"[Ken Duken, Nicole Beharie, Reg E. Cathey]",[Stefan C. Schaefer]
516,2976,Hairspray,"Pleasantly plump teenager, Tracy Turnblad and ...","[Family, Comedy, Music, Romance]","[races, dream, dance, television, tv show, rac...","[John Travolta, Michelle Pfeiffer, Christopher...",[Adam Shankman]

In [21]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [22]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [23]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [24]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [25]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [26]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])

In [27]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [29]:
vector = cv.fit_transform(new['tags']).toarray()

In [30]:
vector.shape

(4806, 5000)

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
similarity = cosine_similarity(vector)

In [33]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])

[(0, 1.0),
 (539, 0.26089696604360174),
 (1192, 0.2581988897471611),
 (260, 0.25110592822973776),
 (1214, 0.24944382578492943),
 (507, 0.24846467329894412),
 (1440, 0.24397501823713333),
 (1916, 0.243599382882345),
 (582, 0.24147264420814754),
 (3728, 0.23904572186687872),
 (74, 0.22677868380553634),
 (3606, 0.2238868314198225),
 (322, 0.22230800575069137),
 (83, 0.22190115272469205),
 (4190, 0.22131333406899523),
 (2329, 0.2173253797873328),
 (1202, 0.21653278478430665),
 (47, 0.2164218276749025),
 (61, 0.2162249910469341),
 (495, 0.2162249910469341),
 (2405, 0.21380899352993948),
 (1533, 0.2125118592516207),
 (942, 0.21251185925162067),
 (972, 0.21251185925162067),
 (466, 0.2114722130550724),
 (1327, 0.21147221305507238),
 (2200, 0.2059714602177749),
 (151, 0.20498001542269692),
 (1199, 0.202837021134844),
 (973, 0.2),
 (4046, 0.1980534816610477),
 (3160, 0.19518001458970666),
 (4405, 0.19518001458970666),
 (1273, 0.19518001458970663),
 (2782, 0.19518001458970663),
 (2969, 0.19477964490741223),
 (3536, 0.19451950503185494),
 (461, 0.1938916835823703),
 (3325, 0.1938916835823703),
 (305, 0.19320245583349133),
 (36, 0.19194297398747862),
 (931, 0.1916629694999819),
 (150, 0.18869127060994534),
 (220, 0.18832944617230335),
 (27, 0.18752289237539815),
 (2997, 0.18752289237539815),
 (300, 0.18708286933869708),
 (1319, 0.18442777839082936),
 (4, 0.1825741858350554),
 (184, 0.1825741858350554),
 (1069, 0.1825741858350554),
 (301, 0.18182745801939793),
 (373, 0.18018749253911176),
 (67, 0.17928429140015903),
 (46, 0.1765469659009499),
 (7, 0.1763834207376394),
 (2727, 0.17622684421256032),
 (1827, 0.17445567519772937),
 (1342, 0.1739313106957345),
 (149, 0.173137462139922),
 (2492, 0.17251638983558856),
 (26, 0.17142857142857143),
 (208, 0.1690308509457033),
 (661, 0.1690308509457033),
 (4008, 0.1690308509457033),
 (108, 0.16903085094570328),
 (838, 0.16903085094570328),
 (1804, 0.16673100431301852),
 (94, 0.16574838603294897),
 (2511, 0.16574838603294897),
 (1392, 0.16408253082847338),
 (581, 0.16265001215808886),
 (1295, 0.16239958858823),
 (4336, 0.16239958858823),
 (168, 0.16035674514745463),
 (1379, 0.16035674514745463),
 (31, 0.15971914124998493),
 (91, 0.15971914124998493),
 (3626, 0.15694120514358612),
 (311, 0.1564921592871903),
 (1961, 0.1553638665664663),
 (502, 0.1546617786679401),
 (111, 0.15430334996209188),
 (577, 0.15430334996209188),
 (3352, 0.15430334996209188),
 (158, 0.15289415743128765),
 (1353, 0.15289415743128765),
 (1176, 0.15179418517972906),
 (2165, 0.15179418517972906),
 (172, 0.15118578920369088),
 (490, 0.15118578920369088),
 (17, 0.15026857675938213),
 (1934, 0.14953343588376802),
 (422, 0.14754222271266348),
 (505, 0.14754222271266348),
 (1484, 0.14754222271266348),
 (41, 0.14638501094227999),
 (84, 0.1456438162508838),
 (52, 0.1449427589131121),
 (557, 0.1449427589131121),
 (568, 0.1449427589131121),
 (2682, 0.1449427589131121),
 (56, 0.14414999403128942),
 (249, 0.14414999403128942),
 (2580, 0.14414999403128942),
 (3997, 0.14414999403128942),
 (332, 0.14285714285714285),
 (1218, 0.14285714285714285),
 (1320, 0.14201432049934523),
 (487, 0.14098147537004826),
 (1325, 0.14098147537004826),
 (187, 0.14085904245475275),
 (1941, 0.14085904245475275),
 (1669, 0.1406421692815486),
 (2129, 0.1406421692815486),
 (2476, 0.1406421692815486),
 (4348, 0.1406421692815486),
 (413, 0.1389425035941821),
 (1829, 0.13801311186847084),
 (2616, 0.13801311186847084),
 (2968, 0.13801311186847084),
 (4490, 0.13801311186847084),
 (2869, 0.13801311186847082),
 (1013, 0.13710212427677043),
 (3407, 0.13710212427677043),
 (3620, 0.13710212427677043),
 (342, 0.13662601021279464),
 (127, 0.13572417850765922),
 (595, 0.13533299049019168),
 (1297, 0.13533299049019168),
 (134, 0.13522468075656266),
 (368, 0.13522468075656266),
 (1156, 0.13522468075656266),
 (3671, 0.1336306209562122),
 (1000, 0.13316902848554255),
 (68, 0.13259870882635919),
 (1045, 0.13259870882635919),
 (1094, 0.13259870882635919),
 (1654, 0.13259870882635919),
 (2374, 0.13259870882635919),
 (3374, 0.13259870882635919),
 (740, 0.13199091933711365),
 (1711, 0.1309307341415954),
 (529, 0.13041013273932528),
 (778, 0.13041013273932528),
 (1613, 0.13041013273932528),
 (483, 0.1301200097264711),
 (1743, 0.1301200097264711),
 (420, 0.12888481555661674),
 (1035, 0.12888481555661674),
 (1737, 0.12880163722232754),
 (238, 0.12777531299998796),
 (939, 0.12777531299998796),
 (2709, 0.12741179785940637),
 (3307, 0.12741179785940637),
 (1571, 0.1267731382092775),
 (4201, 0.1267731382092775),
 (228, 0.12598815766974242),
 (432, 0.12598815766974242),
 (3405, 0.12598815766974242),
 (28, 0.12555296411486888),
 (275, 0.12555296411486888),
 (1272, 0.12555296411486888),
 (2071, 0.12555296411486888),
 (2864, 0.12555296411486888),
 (4673, 0.12555296411486888),
 (549, 0.1246111965698067),
 (95, 0.12461119656980668),
 (50, 0.12344267996967351),
 (72, 0.12344267996967351),
 (579, 0.12344267996967351),
 (1978, 0.12344267996967351),
 (454, 0.12327841818038447),
 (2543, 0.12327841818038447),
 (1508, 0.12327841818038446),
 (653, 0.12298800925361816),
 (808, 0.12298800925361816),
 (123, 0.12198750911856666),
 (692, 0.12073632210407378),
 (1275, 0.12073632210407378),
 (1475, 0.12073632210407378),
 (3145, 0.12036162814275589),
 (169, 0.11952286093343936),
 (624, 0.11952286093343936),
 (2255, 0.11952286093343936),
 (3628, 0.11952286093343936),
 (3719, 0.11952286093343936),
 (166, 0.11952286093343935),
 (232, 0.11952286093343935),
 (294, 0.11952286093343935),
 (687, 0.11952286093343935),
 (859, 0.11952286093343935),
 (1612, 0.11952286093343935),
 (1570, 0.1187013882373396),
 (5, 0.1183452670827877),
 (10, 0.11769797726729994),
 (513, 0.11769797726729994),
 (1029, 0.11769797726729994),
 (2579, 0.11769797726729994),
 (3006, 0.11769797726729994),
 (199, 0.11720180773462385),
 (81, 0.11710800875382396),
 (627, 0.11633501014942217),
 (1369, 0.11633501014942217),
 (1723, 0.11633501014942217),
 (2319, 0.11633501014942217),
 (3998, 0.11633501014942217),
 (4016, 0.11633501014942217),
 (87, 0.11595420713048966),
 (126, 0.11595420713048966),
 (508, 0.11595420713048966),
 (777, 0.11501092655705902),
 (14, 0.11428571428571427),
 (854, 0.11428571428571427),
 (900, 0.11428571428571427),
 (1193, 0.11428571428571427),
 (2009, 0.11428571428571427),
 (2446, 0.11428571428571427),
 (3496, 0.11428571428571427),
 (141, 0.11338934190276817),
 (1520, 0.11338934190276817),
 (1717, 0.11338934190276817),
 (2630, 0.11338934190276817),
 (3659, 0.11338934190276817),
 (4133, 0.11338934190276817),
 (1017, 0.1129384878631564),
 (1493, 0.1129384878631564),
 (2435, 0.1129384878631564),
 (131, 0.1126872339638022),
 (330, 0.1126872339638022),
 (1080, 0.1126872339638022),
 (1292, 0.1126872339638022),
 (3338, 0.1126872339638022),
 (3618, 0.1126872339638022),
 (4095, 0.1126872339638022),
 (18, 0.11194341570991125),
 (102, 0.11194341570991125),
 (2102, 0.11194341570991125),
 (2756, 0.11194341570991125),
 (174, 0.11115400287534567),
 (266, 0.11115400287534567),
 (2068, 0.11115400287534567),
 (2177, 0.11115400287534567),
 (239, 0.11097419040461878),
 (3779, 0.11065666703449763),
 (35, 0.11065666703449761),
 (325, 0.11065666703449761),
 (773, 0.11065666703449761),
 (1154, 0.11065666703449761),
 (2517, 0.11065666703449761),
 (3053, 0.11065666703449761),
 (3952, 0.11065666703449761),
 (403, 0.11002971203391539),
 (295, 0.10968169942141635),
 (312, 0.10968169942141635),
 (535, 0.10968169942141635),
 (986, 0.10968169942141635),
 (1271, 0.10968169942141635),
 (3100, 0.10968169942141635),
 (4077, 0.10968169942141635),
 (754, 0.10826639239215334),
 (4228, 0.10826639239215334),
 (139, 0.10821091383745127),
 (4545, 0.10821091383745125),
 (105, 0.10811249552346706),
 (233, 0.10811249552346706),
 (476, 0.10811249552346706),
 (2452, 0.10811249552346706),
 (2758, 0.10811249552346706),
 (3837, 0.10811249552346706),
 (4196, 0.10811249552346706),
 (4623, 0.10811249552346706),
 (182, 0.10690449676496976),
 (334, 0.10690449676496976),
 (643, 0.10690449676496976),
 (898, 0.10690449676496976),
 (1054, 0.10690449676496976),
 (1107, 0.10690449676496976),
 (3781, 0.10690449676496976),
 (85, 0.10631548679075009),
 (33, 0.1057361065275362),
 (148, 0.1057361065275362),
 (157, 0.1057361065275362),
 (263, 0.1057361065275362),
 (715, 0.1057361065275362),
 (935, 0.1057361065275362),
 (1278, 0.1057361065275362),
 (1299, 0.1057361065275362),
 (1497, 0.1057361065275362),
 (2558, 0.1057361065275362),
 (2656, 0.1057361065275362),
 (4331, 0.1057361065275362),
 (129, 0.10559273546969093),
 (510, 0.10559273546969093),
 (1084, 0.10559273546969093),
 (3441, 0.10559273546969093),
 (3462, 0.10559273546969093),
 (4043, 0.10559273546969093),
 (307, 0.10460520656316097),
 (1231, 0.10432810619146021),
 (400, 0.10350983390135313),
 (660, 0.10350983390135313),
 (781, 0.10350983390135313),
 (1938, 0.10350983390135313),
 (2657, 0.10350983390135313),
 (4254, 0.10350983390135313),
 (270, 0.1031078524452934),
 (278, 0.1031078524452934),
 (279, 0.1031078524452934),
 (371, 0.1031078524452934),
 (870, 0.1031078524452934),
 (1200, 0.1031078524452934),
 (1435, 0.1031078524452934),
 (412, 0.1019294382875251),
 (473, 0.1019294382875251),
 (813, 0.1019294382875251),
 (933, 0.1019294382875251),
 (1274, 0.1019294382875251),
 (1999, 0.1019294382875251),
 (2280, 0.1019294382875251),
 (292, 0.10141851056742199),
 (389, 0.10141851056742199),
 (530, 0.10141851056742199),
 (564, 0.10141851056742199),
 (691, 0.10141851056742199),
 (920, 0.10141851056742199),
 (1075, 0.10141851056742199),
 (1404, 0.10141851056742199),
 (2647, 0.10141851056742199),
 (3091, 0.10141851056742199),
 (3734, 0.10141851056742199),
 (410, 0.10079052613579392),
 (1819, 0.10079052613579392),
 (243, 0.09968895725584535),
 (785, 0.09960238411119947),
 (1087, 0.09960238411119947),
 (791, 0.0994490316197694),
 (1470, 0.0994490316197694),
 (1585, 0.0994490316197694),
 (1682, 0.0994490316197694),
 (1752, 0.0994490316197694),
 (2392, 0.0994490316197694),
 (2648, 0.0994490316197694),
 (589, 0.09862273454430757),
 (618, 0.09862273454430757),
 (1355, 0.09862273454430757),
 (2592, 0.09862273454430757),
 (43, 0.09759000729485333),
 (1842, 0.09759000729485333),
 (2484, 0.09759000729485333),
 (2792, 0.09759000729485333),
 (3152, 0.09759000729485333),
 (23, 0.09759000729485331),
 (142, 0.09759000729485331),
 (236, 0.09759000729485331),
 (362, 0.09759000729485331),
 (2089, 0.09759000729485331),
 (160, 0.09694584179118515),
 (206, 0.09694584179118515),
 (596, 0.09658905768325902),
 (1414, 0.09658905768325902),
 (12, 0.09583148474999097),
 (122, 0.09583148474999097),
 (511, 0.09583148474999097),
 (794, 0.09583148474999097),
 (922, 0.09583148474999097),
 (1025, 0.09583148474999097),
 (1304, 0.09583148474999097),
 (2836, 0.09583148474999097),
 (1828, 0.09561828874675149),
 (1920, 0.09561828874675149),
 (479, 0.09508728264112047),
 (1276, 0.09467621366623016),
 (21, 0.09416472308615166),
 (164, 0.09416472308615166),
 (242, 0.09416472308615166),
 (306, 0.09416472308615166),
 (960, 0.09416472308615166),
 (1247, 0.09416472308615166),
 (1519, 0.09416472308615166),
 (2813, 0.09416472308615166),
 (4468, 0.09416472308615166),
 (799, 0.09390602830316849),
 (1492, 0.09376144618769908),
 (2270, 0.09376144618769908),
 (2384, 0.09376144618769908),
 (2852, 0.09376144618769908),
 (4353, 0.09376144618769908),
 (4502, 0.09376144618769908),
 (4516, 0.09376144618769908),
 (4654, 0.09376144618769908),
 (2444, 0.09333167411831966),
 (75, 0.09258200997725513),
 (227, 0.09258200997725513),
 (349, 0.09258200997725513),
 (356, 0.09258200997725513),
 (369, 0.09258200997725513),
 (775, 0.09258200997725513),
 (901, 0.09258200997725513),
 (978, 0.09258200997725513),
 (1002, 0.09258200997725513),
 (1374, 0.09258200997725513),
 (1696, 0.09258200997725513),
 (1786, 0.09258200997725513),
 (3447, 0.09258200997725513),
 (3535, 0.09258200997725513),
 (3814, 0.09258200997725513),
 (4626, 0.09258200997725513),
 (63, 0.09200874124564722),
 (107, 0.09200874124564722),
 (170, 0.09200874124564722),
 (812, 0.09200874124564722),
 (2001, 0.09200874124564722),
 (2966, 0.09200874124564722),
 (32, 0.09116846116771035),
 (45, 0.09116846116771035),
 (363, 0.09116846116771035),
 (467, 0.09116846116771035),
 (491, 0.09116846116771035),
 (2494, 0.09116846116771035),
 (88, 0.09107651110783743),
 (112, 0.09107651110783743),
 (121, 0.09107651110783743),
 (245, 0.09107651110783743),
 (315, 0.09107651110783743),
 (814, 0.09107651110783743),
 (894, 0.09107651110783743),
 (937, 0.09107651110783743),
 (2163, 0.09107651110783743),
 (3299, 0.09107651110783743),
 (222, 0.09035079029052512),
 (381, 0.09035079029052512),
 (2876, 0.09035079029052512),
 (4737, 0.09035079029052512),
 (2382, 0.09009374626955588),
 (1, 0.08964214570007951),
 (96, 0.08964214570007951),
 (241, 0.08964214570007951),
 (547, 0.08964214570007951),
 (1111, 0.08964214570007951),
 (1140, 0.08964214570007951),
 (1267, 0.08964214570007951),
 (2243, 0.08964214570007951),
 (2247, 0.08964214570007951),
 (2300, 0.08964214570007951),
 (2790, 0.08964214570007951),
 (3089, 0.08964214570007951),
 (4257, 0.08964214570007951),
 (4657, 0.08964214570007951),
 (654, 0.089554732567929),
 (1280, 0.089554732567929),
 (103, 0.08877935232369503),
 (230, 0.08877935232369503),
 (1874, 0.08877935232369503),
 (39, 0.08827348295047496),
 (86, 0.08827348295047496),
 (98, 0.08827348295047496),
 (101, 0.08827348295047496),
 (203, 0.08827348295047496),
 (786, 0.08827348295047496),
 (899, 0.08827348295047496),
 (1205, 0.08827348295047496),
 (1469, 0.08827348295047496),
 (3426, 0.08827348295047495),
 (501, 0.0880237696271323),
 (1824, 0.0880237696271323),
 (19, 0.08728715609439694),
 (193, 0.08728715609439694),
 (1137, 0.08728715609439694),
 (1401, 0.08728715609439694),
 (2095, 0.08728715609439694),
 (2246, 0.08728715609439694),
 (2335, 0.08728715609439694),
 (3067, 0.08728715609439694),
 (3216, 0.08728715609439694),
 (3439, 0.08728715609439694),
 (4163, 0.08728715609439694),
 (4492, 0.08728715609439694),
 (4718, 0.08728715609439694),
 (257, 0.08696565534786725),
 (457, 0.08696565534786725),
 (626, 0.08696565534786725),
 (746, 0.08696565534786725),
 (787, 0.08696565534786725),
 (3026, 0.08696565534786725),
 (3138, 0.08696565534786725),
 (3233, 0.08696565534786725),
 (3308, 0.08696565534786725),
 (3421, 0.08696565534786725),
 (153, 0.086568731069961),
 (1894, 0.086568731069961),
 (1530, 0.08656873106996099),
 (51, 0.08586775814821836),
 (1635, 0.08586775814821836),
 (207, 0.0857142857142857),
 (634, 0.0857142857142857),
 (1159, 0.0857142857142857),
 (2249, 0.0857142857142857),
 (2640, 0.0857142857142857),
 (572, 0.08518354199999197),
 (1922, 0.08518354199999197),
 (3429, 0.08518354199999197),
 (37, 0.08451542547285165),
 (472, 0.08451542547285165),
 (534, 0.08451542547285165),
 (680, 0.08451542547285165),
 (776, 0.08451542547285165),
 (885, 0.08451542547285165),
 (985, 0.08451542547285165),
 (1397, 0.08451542547285165),
 (1610, 0.08451542547285165),
 (1617, 0.08451542547285165),
 (1651, 0.08451542547285165),
 (2161, 0.08451542547285165),
 (2199, 0.08451542547285165),
 (2708, 0.08451542547285165),
 (2797, 0.08451542547285165),
 (3387, 0.08451542547285165),
 (3525, 0.08451542547285165),
 (4059, 0.08451542547285165),
 (4431, 0.08451542547285165),
 (4641, 0.08451542547285165),
 (190, 0.08386278693775347),
 (82, 0.08336550215650926),
 (223, 0.08336550215650926),
 (254, 0.08336550215650926),
 (329, 0.08336550215650926),
 (471, 0.08336550215650926),
 (503, 0.08336550215650926),
 (632, 0.08336550215650926),
 (2679, 0.08336550215650926),
 (3353, 0.08336550215650926),
 (3468, 0.08336550215650926),
 (3908, 0.08336550215650926),
 (16, 0.08226127456606226),
 (71, 0.08226127456606226),
 (138, 0.08226127456606226),
 (1556, 0.08226127456606226),
 (1761, 0.08226127456606226),
 (2816, 0.08226127456606226),
 (4053, 0.08226127456606226),
 (4451, 0.08226127456606226),
 (62, 0.08199200616907877),
 (189, 0.08199200616907877),
 (205, 0.08199200616907877),
 (256, 0.08199200616907877),
 (850, 0.08199200616907877),
 (1043, 0.08199200616907877),
 (1321, 0.08199200616907877),
 (1660, 0.08199200616907877),
 (2322, 0.08199200616907877),
 (2759, 0.08199200616907877),
 (2785, 0.08199200616907877),
 (2880, 0.08199200616907877),
 (3153, 0.08199200616907877),
 (3251, 0.08199200616907877),
 (4473, 0.08199200616907877),
 (4568, 0.08199200616907877),
 (11, 0.081199794294115),
 (70, 0.081199794294115),
 (365, 0.081199794294115),
 (1287, 0.081199794294115),
 (1288, 0.081199794294115),
 (1363, 0.081199794294115),
 (2588, 0.081199794294115),
 (3204, 0.081199794294115),
 (3699, 0.081199794294115),
 (274, 0.08058229640253803),
 (59, 0.08024108542850393),
 (587, 0.08017837257372731),
 (737, 0.08017837257372731),
 (2159, 0.08017837257372731),
 (4640, 0.08017837257372731),
 (125, 0.07985957062499247),
 (109, 0.07968190728895957),
 (313, 0.07968190728895957),
 (800, 0.07968190728895957),
 (1286, 0.07968190728895957),
 (1517, 0.07968190728895957),
 (2157, 0.07968190728895957),
 (2313, 0.07968190728895957),
 (2377, 0.07968190728895957),
 (2406, 0.07968190728895957),
 (2547, 0.07968190728895957),
 (2655, 0.07968190728895957),
 (3396, 0.07968190728895957),
 (3428, 0.07968190728895957),
 (3830, 0.07968190728895957),
 (4412, 0.07968190728895957),
 (271, 0.0791945516022682),
 (732, 0.0791945516022682),
 (908, 0.0791945516022682),
 (2391, 0.0791945516022682),
 (2827, 0.0791945516022682),
 (3020, 0.0791945516022682),
 (3905, 0.0791945516022682),
 (229, 0.07913425882489307),
 (76, 0.07824607964359516),
 (79, 0.07824607964359516),
 (543, 0.07824607964359516),
 (591, 0.07824607964359516),
 (784, 0.07824607964359516),
 (977, 0.07824607964359516),
 (1173, 0.07824607964359516),
 (1323, 0.07824607964359516),
 (2017, 0.07824607964359516),
 (2048, 0.07824607964359516),
 (2359, 0.07824607964359516),
 (2697, 0.07824607964359516),
 (2914, 0.07824607964359516),
 (4081, 0.07824607964359516),
 (4121, 0.07824607964359516),
 (2350, 0.07824607964359515),
 (200, 0.07755667343294811),
 (1003, 0.07755667343294811),
 (1346, 0.07755667343294811),
 (1765, 0.07755667343294811),
 (2132, 0.07755667343294811),
 (2208, 0.07755667343294811),
 (3070, 0.07755667343294811),
 (3980, 0.07755667343294811),
 (4004, 0.07755667343294811),
 (9, 0.07733088933397005),
 (536, 0.07733088933397005),
 (674, 0.07733088933397005),
 (1619, 0.07733088933397005),
 (1628, 0.07733088933397005),
 (2237, 0.07733088933397005),
 (3186, 0.07733088933397005),
 (55, 0.07655590023509526),
 (212, 0.07644707871564382),
 (419, 0.07644707871564382),
 (782, 0.07644707871564382),
 (1442, 0.07644707871564382),
 (1879, 0.07644707871564382),
 (2646, 0.07644707871564382),
 (488, 0.07606982611289638),
 (179, 0.07559289460184544),
 (267, 0.07559289460184544),
 (570, 0.07559289460184544),
 (728, 0.07559289460184544),
 (827, 0.07559289460184544),
 (1144, 0.07559289460184544),
 (1166, 0.07559289460184544),
 (1290, 0.07559289460184544),
 (1766, 0.07559289460184544),
 (2529, 0.07559289460184544),
 (2694, 0.07559289460184544),
 (2783, 0.07559289460184544),
 (3388, 0.07559289460184544),
 (3820, 0.07559289460184544),
 (3992, 0.07559289460184544),
 (4097, 0.07559289460184544),
 (4403, 0.07559289460184544),
 (4443, 0.07559289460184544),
 (2052, 0.07476671794188403),
 (97, 0.07476671794188401),
 (262, 0.07476671794188401),
 (635, 0.07476671794188401),
 (665, 0.07476671794188401),
 (995, 0.07476671794188401),
 (1338, 0.07476671794188401),
 (1697, 0.07476671794188401),
 (1992, 0.07476671794188401),
 (183, 0.07466533929465573),
 (215, 0.07396705090823068),
 (704, 0.07396705090823068),
 (752, 0.07396705090823068),
 (1016, 0.07396705090823068),
 (2014, 0.07396705090823068),
 (2316, 0.07396705090823068),
 (4343, 0.07396705090823068),
 (100, 0.07377111135633174),
 (336, 0.07377111135633174),
 (1164, 0.07377111135633174),
 (1260, 0.07377111135633174),
 (1733, 0.07377111135633174),
 (1770, 0.07377111135633174),
 (1986, 0.07377111135633174),
 (2110, 0.07377111135633174),
 (3239, 0.07377111135633174),
 (3667, 0.07377111135633174),
 (3974, 0.07377111135633174),
 (4290, 0.07377111135633174),
 (30, 0.07319250547113999),

In [34]:
new_df = movies[['movie_id', 'title', 'tags']]

In [35]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [36]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [37]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Ender's Game
Aliens vs Predator: Requiem
Independence Day

In [38]:
recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan

In [39]:
recommend('Tangled')

Aladdin
Toy Story 3
The Princess and the Frog
Frozen
The Smurfs

In [40]:
recommend('Spider-Man')

Spider-Man 3
Spider-Man 2
The Amazing Spider-Man 2
The Amazing Spider-Man
Arachnophobia

In [41]:
recommend('Robin Hood')

Robin Hood: Prince of Thieves
Rango
Nicholas Nickleby
I Am Number Four
Puss in Boots

In [42]:
recommend('Batman')

Batman
Batman & Robin
The Dark Knight Rises
Batman Begins
Batman Returns

In [43]:
recommend('King Kong')

The Black Hole
20,000 Leagues Under the Sea
Supporting Characters
Ice Age: Continental Drift
Serenity

In [44]:
recommend('Jurassic World')

Jurassic Park
The Lost World: Jurassic Park
Journey to the Center of the Earth
A Sound of Thunder
Walking With Dinosaurs

In [45]:
recommend('Superman')

Superman II
Superman Returns
Superman III
Superman IV: The Quest for Peace
Man of Steel

In [46]:
recommend('Iron Man')

Iron Man 2
Iron Man 3
Avengers: Age of Ultron
Captain America: Civil War
The Avengers

In [47]:
recommend('Titanic')

Captain Phillips
The Notebook
In the Heart of the Sea
Ghost Ship
Poseidon

In [48]:
recommend('Mission: Impossible')

Mission: Impossible II
Mission: Impossible III
Bad Company
Dying of the Light
The November Man

In [49]:
recommend('The Matrix')

The Matrix Revolutions
The Matrix Reloaded
Jupiter Ascending
Sleep Dealer
Æon Flux

In [50]:
recommend('Star Wars')

The Ultimate Gift
Big Fat Liar
Friday the 13th Part VI: Jason Lives
Friday the 13th Part VIII: Jason Takes Manhattan
Jason Goes to Hell: The Final Friday

In [51]:
recommend('Hotel Transylvania')

Hotel Transylvania 2
The Smurfs
The Croods
Dracula 2000
The Boxtrolls

In [52]:
recommend('Despicable Me')

Despicable Me 2
Up
Minions
The Boxtrolls
Ice Age: Dawn of the Dinosaurs

In [53]:
recommend('Train')

The Evil Dead
Evil Dead
Army of Darkness
The Cabin in the Woods
Krampus

In [54]:
recommend('Inside Out')

Up
Raising Helen
The Cookout
Alvin and the Chipmunks: The Road Chip
Synecdoche, New York

In [55]:
import pickle

In [56]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [57]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [58]:
pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))

In [ ]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))